{
 "title": "Salezi",
 "description": "stock and Price ",
 "time": { "from": "2023-11-27T18:31:53.746Z", "to": "2023-11-28T06:31:53.746Z" },
 "panels": [
  {
   "title": "Global Stock",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT type, SUM(stock) AS total_stock\nFROM (\n    SELECT 'book' AS type, stock FROM books\n    UNION ALL\n    SELECT 'cd' AS type, stock FROM cds\n    UNION ALL\n    SELECT 'electronic' AS type, stock FROM electronics\n) AS all_products\nGROUP BY type;\n",
     "rawQueryText": "SELECT type, SUM(stock) AS total_stock\nFROM (\n    SELECT 'book' AS type, stock FROM books\n    UNION ALL\n    SELECT 'cd' AS type, stock FROM cds\n    UNION ALL\n    SELECT 'electronic' AS type, stock FROM electronics\n) AS all_products\nGROUP BY type;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Books stocks",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT title, Stock From books\n",
     "rawQueryText": "SELECT title, Stock From books\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Stock CD",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT title,stock FROM CDS",
     "rawQueryText": "SELECT title,stock FROM CDS",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Stock electronics",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT model, stock from electronics",
     "rawQueryText": "SELECT model, stock from electronics",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total Price per Category",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT type, stock AS total_stock, price AS total_price\nFROM (\n    SELECT 'book' AS type, stock, price FROM books\n    UNION ALL\n    SELECT 'cd' AS type, stock, price FROM cds\n    UNION ALL\n    SELECT 'electronic' AS type, stock, price FROM electronics\n) AS all_products\n\n",
     "rawQueryText": "SELECT type, stock AS total_stock, price AS total_price\nFROM (\n    SELECT 'book' AS type, stock, price FROM books\n    UNION ALL\n    SELECT 'cd' AS type, stock, price FROM cds\n    UNION ALL\n    SELECT 'electronic' AS type, stock, price FROM electronics\n) AS all_products\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Books Price",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT title, price FROM books",
     "rawQueryText": "SELECT title, price FROM books",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CD Price",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT price, title from cds",
     "rawQueryText": "SELECT price, title from cds",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Electronics Price",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT model, price from electronics",
     "rawQueryText": "SELECT model, price from electronics",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}